<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Extension;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;
use Symfony\Component\Config\Definition\Exception\Exception;

/**
 * ExtensionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtensionRepository extends \Doctrine\ORM\EntityRepository
{

}
